apiVersion: k8spin.cloud/v1
kind: Space
metadata:
  namespace: org-example-tenant-crm
  name: int
spec:
  resources:
    cpu: "2"
    memory: "1G"
  containers:
    defaults:
      resources:
        cpu: 10m
        memory: 32Mi
  allowIncomingNetwork:
    organizations:
      - organization_name: example
    tenants:
      - organization_name: example
        tenant_name: crm
    spaces:
      - organization_name: example
        tenant_name: crm
        space_name: stg
---
apiVersion: k8spin.cloud/v1
kind: Space
metadata:
  namespace: org-example-tenant-crm
  name: pro
spec:
  resources:
    cpu: "3"
    memory: "2G"
  containers:
    defaults:
      resources:
        cpu: 10m
        memory: 32Mi